name: Unit Tests
on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.23.x, 1.24.x]
        platform: [ubuntu-22.04, ubuntu-24.04-arm, windows-latest]
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Get the k6 version
        id: get_k6_version
        run: |
          echo "Running tests on '${GITHUB_REF}' with '$(git describe --tags --always --long --dirty)' checked out..."
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: Install chromium
        # This is only needed on arm images, chromium comes preinstalled on amd64 runner images.
        if: contains(matrix.platform, 'arm')
        run: |
          sudo apt update && sudo apt install chromium-browser
          chromium --version
      - name: Run tests
        run: |
          set -x
          go version
          export GOMAXPROCS=2
          args=("-p" "2" "-race")
          # Run with less concurrency on Windows/MacOS to minimize flakiness.
          if [[ "${{ matrix.platform }}" == windows* || "${{ matrix.platform }}" == macos* ]]; then
            unset args[2]
            args[1]="1"
            export GOMAXPROCS=1
          fi
          go test "${args[@]}" -timeout 800s ./...

  test-tip:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04, ubuntu-24.04-arm, windows-latest]
    runs-on: ${{ matrix.platform }}
    continue-on-error: true
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Download Go tip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download ${{ matrix.platform }} --repo grafana/gotip --pattern 'go.zip'
      - name: Install Go tip
        run: |
          unzip go.zip -d $HOME/sdk
          echo "GOROOT=$HOME/sdk/gotip" >> "$GITHUB_ENV"
          echo "GOPATH=$HOME/go" >> "$GITHUB_ENV"
          echo "$HOME/go/bin" >> "$GITHUB_PATH"
          echo "$HOME/sdk/gotip/bin" >> "$GITHUB_PATH"
      - name: Install chromium
        # This is only needed on arm images, chromium comes preinstalled on amd64 runner images.
        if: contains(matrix.platform, 'arm')
        run: |
          sudo apt update && sudo apt install chromium-browser
          chromium --version
      - name: Run tests
        run: |
          set -x
          which go
          go version
          export GOMAXPROCS=2
          args=("-p" "2" "-race")
          # Run with less concurrency on Windows/MacOS to minimize flakiness.
          if [[ "${{ matrix.platform }}" == windows* || "${{ matrix.platform }}" == macos* ]]; then
            unset args[2]
            args[1]="1"
            export GOMAXPROCS=1
          fi
          go test "${args[@]}" -timeout 800s ./...
